###
#  Defines CI/CD for project
##

language: node_js

service_name: travis-pro

node_js:
  - 4
  - 6
  - 7
# node_js

after_success:
  - npm run code-climate
  - npm run coveralls
# after_success

# .travis.yml